In [6]:
import numpy as np
np.random.seed(0)
a = np.random.randint(0, 2, size = (3,3))
a

array([[0, 1, 1],
       [0, 1, 1],
       [1, 1, 1]], dtype=int32)

In [9]:
a.shape

(3, 3)

In [11]:
r, c = a.shape
r,c

(3, 3)

In [ ]:
for i in range(0,r):
    for k in range(0,c):
        if a[i][k] == 1:
            if k + 1 < c:
                if a[i][k+1] == 1:
                    if i+1 < r:
                        if a[i+1][k] == 1:
                            if a[i+1][k+1] == 1:
                                print(a[i:,k:])

[[1 1]
 [1 1]
 [1 1]]
[[1 1]
 [1 1]]


In [27]:
a[1:,1:]

array([[1, 1],
       [1, 1]], dtype=int32)